<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX71nugv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX71nugv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerX71nugv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerX71nugv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerX71nugv\appProdProjectContainer(array(
    'container.build_hash' => 'X71nugv',
    'container.build_id' => '5d50c9a7',
    'container.build_time' => 1548528696,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX71nugv');
