<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\DefaultController:indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.n5nyu1h']) ? $this->services['service_locator.n5nyu1h'] : $this->load('getServiceLocator_N5nyu1hService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceController:createAction' => function () {
    return ${($_ = isset($this->services['service_locator.m5u9apb']) ? $this->services['service_locator.m5u9apb'] : $this->load('getServiceLocator_M5u9apbService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceController:detailsAction' => function () {
    return ${($_ = isset($this->services['service_locator.hfpl6y9']) ? $this->services['service_locator.hfpl6y9'] : $this->load('getServiceLocator_Hfpl6y9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceController:editAction' => function () {
    return ${($_ = isset($this->services['service_locator.hfpl6y9']) ? $this->services['service_locator.hfpl6y9'] : $this->load('getServiceLocator_Hfpl6y9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceController:listAction' => function () {
    return ${($_ = isset($this->services['service_locator.m5u9apb']) ? $this->services['service_locator.m5u9apb'] : $this->load('getServiceLocator_M5u9apbService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceController:lockAction' => function () {
    return ${($_ = isset($this->services['service_locator.hfpl6y9']) ? $this->services['service_locator.hfpl6y9'] : $this->load('getServiceLocator_Hfpl6y9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceProductController:addAction' => function () {
    return ${($_ = isset($this->services['service_locator.nqn1yqe']) ? $this->services['service_locator.nqn1yqe'] : $this->load('getServiceLocator_Nqn1yqeService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProductController:createAction' => function () {
    return ${($_ = isset($this->services['service_locator.8fhgkaz']) ? $this->services['service_locator.8fhgkaz'] : $this->load('getServiceLocator_8fhgkazService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProductController:deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.qck8vx0']) ? $this->services['service_locator.qck8vx0'] : $this->load('getServiceLocator_Qck8vx0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProductController:editAction' => function () {
    return ${($_ = isset($this->services['service_locator.qck8vx0']) ? $this->services['service_locator.qck8vx0'] : $this->load('getServiceLocator_Qck8vx0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProductController:listAction' => function () {
    return ${($_ = isset($this->services['service_locator.8fhgkaz']) ? $this->services['service_locator.8fhgkaz'] : $this->load('getServiceLocator_8fhgkazService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:changeStateAction' => function () {
    return ${($_ = isset($this->services['service_locator.gji1hzy']) ? $this->services['service_locator.gji1hzy'] : $this->load('getServiceLocator_Gji1hzyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:createAction' => function () {
    return ${($_ = isset($this->services['service_locator.psrccnr']) ? $this->services['service_locator.psrccnr'] : $this->load('getServiceLocator_PsrccnrService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.gji1hzy']) ? $this->services['service_locator.gji1hzy'] : $this->load('getServiceLocator_Gji1hzyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:editAction' => function () {
    return ${($_ = isset($this->services['service_locator.maijhzr']) ? $this->services['service_locator.maijhzr'] : $this->load('getServiceLocator_MaijhzrService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:listAction' => function () {
    return ${($_ = isset($this->services['service_locator.zk23vy9']) ? $this->services['service_locator.zk23vy9'] : $this->load('getServiceLocator_Zk23vy9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController::indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.n5nyu1h']) ? $this->services['service_locator.n5nyu1h'] : $this->load('getServiceLocator_N5nyu1hService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceController::createAction' => function () {
    return ${($_ = isset($this->services['service_locator.m5u9apb']) ? $this->services['service_locator.m5u9apb'] : $this->load('getServiceLocator_M5u9apbService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceController::detailsAction' => function () {
    return ${($_ = isset($this->services['service_locator.hfpl6y9']) ? $this->services['service_locator.hfpl6y9'] : $this->load('getServiceLocator_Hfpl6y9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceController::editAction' => function () {
    return ${($_ = isset($this->services['service_locator.hfpl6y9']) ? $this->services['service_locator.hfpl6y9'] : $this->load('getServiceLocator_Hfpl6y9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceController::listAction' => function () {
    return ${($_ = isset($this->services['service_locator.m5u9apb']) ? $this->services['service_locator.m5u9apb'] : $this->load('getServiceLocator_M5u9apbService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceController::lockAction' => function () {
    return ${($_ = isset($this->services['service_locator.hfpl6y9']) ? $this->services['service_locator.hfpl6y9'] : $this->load('getServiceLocator_Hfpl6y9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\InvoiceProductController::addAction' => function () {
    return ${($_ = isset($this->services['service_locator.nqn1yqe']) ? $this->services['service_locator.nqn1yqe'] : $this->load('getServiceLocator_Nqn1yqeService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProductController::createAction' => function () {
    return ${($_ = isset($this->services['service_locator.8fhgkaz']) ? $this->services['service_locator.8fhgkaz'] : $this->load('getServiceLocator_8fhgkazService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProductController::deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.qck8vx0']) ? $this->services['service_locator.qck8vx0'] : $this->load('getServiceLocator_Qck8vx0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProductController::editAction' => function () {
    return ${($_ = isset($this->services['service_locator.qck8vx0']) ? $this->services['service_locator.qck8vx0'] : $this->load('getServiceLocator_Qck8vx0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProductController::listAction' => function () {
    return ${($_ = isset($this->services['service_locator.8fhgkaz']) ? $this->services['service_locator.8fhgkaz'] : $this->load('getServiceLocator_8fhgkazService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::changeStateAction' => function () {
    return ${($_ = isset($this->services['service_locator.gji1hzy']) ? $this->services['service_locator.gji1hzy'] : $this->load('getServiceLocator_Gji1hzyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::createAction' => function () {
    return ${($_ = isset($this->services['service_locator.psrccnr']) ? $this->services['service_locator.psrccnr'] : $this->load('getServiceLocator_PsrccnrService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.gji1hzy']) ? $this->services['service_locator.gji1hzy'] : $this->load('getServiceLocator_Gji1hzyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::editAction' => function () {
    return ${($_ = isset($this->services['service_locator.maijhzr']) ? $this->services['service_locator.maijhzr'] : $this->load('getServiceLocator_MaijhzrService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::listAction' => function () {
    return ${($_ = isset($this->services['service_locator.zk23vy9']) ? $this->services['service_locator.zk23vy9'] : $this->load('getServiceLocator_Zk23vy9Service.php')) && false ?: '_'};
})));
