<?php

namespace AppBundle\Repository;

/**
 * Invoice_ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Invoice_ProductRepository extends \Doctrine\ORM\EntityRepository
{
}
